### ISSUE TITLE
Shopfloor: question regarding the beta development status and future plans

### ISSUE THREAD

**Issue by wytzejan** [OCA/wms#611]
Hello,

I have a customer who like to upgrade to Odoo v16. They currently have a custom written barcode scanning interface to manage outgoing deliveries but they very much like Shopfloor. I saw the development status of Shopfloor in v14 is still beta. Does anybody knows if there are companies who use Shopfloor v14 in production? And if so, is it safe to use?
Further more, I don't see anyone working on a migration to v15 for Shopfloor. Are there people here planning to do so? I'm happy to help but it seems quite an effort. For example, in the manifest of v14 there are a lot of TODO's related to deps.

**Comment by wytzejan** [comment]
@simahawk Hi! Do you have any thoughs on this? I'd love to hear.

**Comment by simahawk** [comment]
@wytzejan hello,

Here ares some answers.

The fact that a module is marked as "Beta" does not mean it's not used in prod. Even "Alpha" can be used in prod.
Sometimes - and probably is the case for SF - we keep dev status low just to have a little bit more freedom to change some implementations. In any case, we try hard to never introduce backward incompatible changes whenever possible.

v14 is used in prod since years and in constant evolution, no worries about this ;)
v15 has been drafted by @flachica and there are some pending PRs (unfortunately I never had time to review them).
v16 will happen, probably soon. There are some evolution in the rest-framework that we have to consider before migrating everything as is. 

Regarding TODOs: they are not blocker. We just left a trace of what could be improved.

Hope this helps.

**Comment by huahyong** [comment]
Ciao @simahawk, 
Sorry if I'm reopening this question. I'm starting to dig into SF. I've taken a look at SF 16.0 PRs. So, have you decided to stick with base_rest, or are you working on a FastAPI migration behind the curtain? Just to be clear, I'm not requesting a migration. I'm agnostic about it; I just want to know which path to follow for a shopfloor_manufacture implementation.
Thank you very much for your time and effort.

**Comment by simahawk** [comment]
We decided to move on w/ base_rest for the time being. Main reason: we needed SF ASAP on v16 and Fastapi integration was not merged / ready yet.
